mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.daofeng.system.entity
  map-underscore-to-camel-case: true

server:
  port: 8081
  servlet:
    session:
      #Session超时时间设置为5小时，单位是秒，默认是30分钟
      timeout: 18000

spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 配置日期格式化
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
#日志=============================================================================================
logging:
  level:
    root: error #日志配置DEBUG,INFO,WARN,ERROR
